### ISSUE TITLE
Do you plan to support select ?

### ISSUE THREAD

**Issue by mackoj** [czechboy0/Socks#14]
Hi @czechboy0 and @MatthiasKreileder !

Thanks for open sourcing this lib.
I love to read and study other people code it's a great way to learn.

Do you plan to support something like `select`(POSIX) which is crucial when building a server with socket ? Or [libevent](http://libevent.org) which work on Windows, OS X, Linux ?

Cheers,

**Comment by czechboy0** [comment]
Hi @mackoj,

Yes absolutely. It's actually on the list in #2. We just haven't gotten around to it. :blush: 

(We'd welcome a PR if you're happy to add it yourself)
