### ISSUE TITLE
`closed` property on socket

### ISSUE THREAD

**Issue by tannernelson** [czechboy0/Socks#35]
To perform HTTP parsing, serialization, and keep-alive on sockets it's important to know whether or not the socket has closed.

Most socket libs include a `closed: Bool` property on the socket. 

This property may or may not need to be updated if the socket is closed by the client or closed in other ways. It might not be enough to set the flag to true when the socket is closed by calling `.close()`

**Comment by czechboy0** [comment]
I'll add this, but can you add more info on *when* this flag should be turned on? Definitely on `.close()`, but maybe also when an error is emitted? Any other cases?

**Comment by tannernelson** [comment]
I'll research this and see what other socket libs do.

**Comment by czechboy0** [comment]
Fixed by #38, but if you find any other case when `closed` should be set, please comment here, @tannernelson.
