### ISSUE TITLE
Add timeout to send/recv

### ISSUE THREAD

**Issue by tannernelson** [czechboy0/Socks#48]
Socks should expose a way to configure the `SO_RCVTIMEO` and `SO_SNDTIMEO`.

This will allow us to conform to the C7 spec:

```swift
public func send(_ data: Data, timingOut deadline: Double) throws
```

And it will help frameworks using Socks to avoid memory leaks from dead connections that never close.

**Comment by czechboy0** [comment]
Related to #30.

Agreed, I'll investigate and report back.
