### ISSUE TITLE
Making the TCPClient class final

### ISSUE THREAD

**Issue by tannernelson** [czechboy0/Socks#55]
Making the TCPClient class final could potentially give some performance benefits since the compiler could use direct method calls.

**Comment by czechboy0** [comment]
Does `final` still allow adding extensions?

**Comment by tannernelson** [comment]
It should only prevent subclassing. Extensions seem like they will always be dynamic class. Probably no way to optimize that.

**Comment by tannernelson** [comment]
I didn't know you had the intent to allow subclassing on TCP client.

If that is the case, then the end user can make a final subclass themselves if they need the added performance.
